### ISSUE TITLE
Four of these files are invalid: please correct them

### ISSUE THREAD

**Issue by lb42** [COST-ELTeC/ELTeC-por#1]
/home/lou/Public/ELTeC-por/level1/PT0011.eltec:110:34: error: text not allowed here; expected the element end-tag or element "bibl", "div", "gap", "head", "l", "label", "milestone", "note", "p", "pb" or "quote"

/home/lou/Public/ELTeC-por/level1/PT0015.eltec:34:3: fatal: The element type "bibl" must be terminated by the matching end-tag "</bibl>".

/home/lou/Public/ELTeC-por/level1/PT0031.eltec:179:10: error: element "foreign" not allowed here; expected the element end-tag or element "bibl", "div", "gap", "l", "label", "milestone", "note", "p", "pb", "quote" or "trailer"
/home/lou/Public/ELTeC-por/level1/PT0031.eltec:1299:2: error: text not allowed here; expected the element end-tag or element "bibl", "div", "gap", "l", "label", "milestone", "note", "p", "pb", "quote" or "trailer"

/home/lou/Public/ELTeC-por/level1/PT0036.eltec:1379:10: error: element "foreign" not allowed here; expected the element end-tag or element "bibl", "div", "gap", "l", "label", "milestone", "note", "p", "pb", "quote" or "trailer"
/home/lou/Public/ELTeC-por/level1/PT0036.eltec:1380:4: error: element "p" not allowed here; expected the element end-tag, text or element "corr", "date", "emph", "foreign", "gap", "hi", "measure", "milestone", "name", "note", "pb", "quote", "ref", "term" or "title"

**Comment by dianamsmpsantos** [comment]
Are these still unsolved problems?

**Comment by lb42** [comment]
Presumably, but since the filenames have changed it's impossible to tell. In any case, all the files currently in ELTeC-por are currently valid, so I am closing this.
